from typing import Any


def build_pr_body(
    *,
    user_task: str,
    planner_summary: str,
    verifier_result: dict[str, Any],
    reviewer_result: dict[str, Any],
    changed_files: list[str],
    test_command: list[str] | None,
) -> str:
    verifier_status = "passed" if verifier_result.get("passed") else "failed"
    reviewer_status = "approved" if reviewer_result.get("approved") else "rejected"

    changed = "\n".join(f"- `{path}`" for path in changed_files) or "- None"

    return f"""## Summary

Generated by AgentBus for:

> {user_task}

Planner summary: {planner_summary}

Reviewer: {reviewer_status}

## Verification

- Status: {verifier_status}
- Command: `{test_command or verifier_result.get("command") or []}`
- Reason: {verifier_result.get("reason", "Not provided")}

## Changed Files

{changed}

## Reviewer Notes

{reviewer_result.get("summary", "No reviewer summary.")}

## Safety Notes

- AgentBus does not force push.
- AgentBus does not deploy or apply infrastructure.
- PR creation was explicitly requested.
"""
