"""Versioned execution tracing primitives for AgentBus."""

from agentbus.trace.context import (
    TraceContext,
    copy_trace_context,
    current_trace_context,
    reset_trace_context,
    set_trace_context,
    trace_context,
)
from agentbus.trace.errors import (
    TraceError,
    TraceIntegrityError,
    TraceNotFoundError,
    TraceValidationError,
)
from agentbus.trace.models import (
    ReplayMode,
    Trace,
    TraceArtifactReference,
    TraceCheckpoint,
    TraceEvent,
    TraceFailure,
    TraceInput,
    TraceLink,
    TraceLinkType,
    TraceOutput,
    TraceReplayMetadata,
    TraceResourceUsage,
    TraceSpan,
    TraceSpanType,
    TraceStatus,
    TraceValueReference,
)
from agentbus.trace.version import TRACE_SCHEMA_NAME, TRACE_SCHEMA_VERSION

__all__ = [
    "ReplayMode",
    "TRACE_SCHEMA_NAME",
    "TRACE_SCHEMA_VERSION",
    "Trace",
    "TraceArtifactReference",
    "TraceCheckpoint",
    "TraceContext",
    "TraceError",
    "TraceEvent",
    "TraceFailure",
    "TraceInput",
    "TraceIntegrityError",
    "TraceLink",
    "TraceLinkType",
    "TraceNotFoundError",
    "TraceOutput",
    "TraceReplayMetadata",
    "TraceResourceUsage",
    "TraceSpan",
    "TraceSpanType",
    "TraceStatus",
    "TraceValidationError",
    "TraceValueReference",
    "copy_trace_context",
    "current_trace_context",
    "reset_trace_context",
    "set_trace_context",
    "trace_context",
]
