"""Versioned execution tracing primitives for AgentBus."""

from agentbus.trace.context import (
    TraceContext,
    copy_trace_context,
    current_trace_context,
    reset_trace_context,
    set_trace_context,
    trace_context,
)
from agentbus.trace.errors import (
    TraceError,
    TraceIntegrityError,
    TraceNotFoundError,
    TraceObjectTooLargeError,
    TraceRecordingError,
    TraceSecretRejectedError,
    TraceStorageError,
    TraceValidationError,
)
from agentbus.trace.blobs import (
    BLOB_SCHEMA_VERSION,
    BlobMetadata,
    RetentionClass,
    StoredBlob,
)
from agentbus.trace.events import TraceEventType
from agentbus.trace.models import (
    ReplayMode,
    Trace,
    TraceArtifactReference,
    TraceCheckpoint,
    TraceEvent,
    TraceFailure,
    TraceInput,
    TraceLink,
    TraceLinkType,
    TraceOutput,
    TraceReplayMetadata,
    TraceResourceUsage,
    TraceSpan,
    TraceSpanType,
    TraceStatus,
    TraceValueReference,
)
from agentbus.trace.version import TRACE_SCHEMA_NAME, TRACE_SCHEMA_VERSION
from agentbus.trace.recorder import TraceRecorder, TraceSink
from agentbus.trace.persistence import StateStoreTraceSink
from agentbus.trace.provenance import (
    PROVENANCE_INTEGRITY_ALGORITHM,
    PROVENANCE_SCHEMA_VERSION,
    EventStreamRange,
    ProvenanceBuilder,
    ProvenanceIntegrityEntry,
    ProvenanceManifest,
    ProviderRouteProvenance,
    ReplayabilityLevel,
    ToolDescriptorProvenance,
    verify_provenance,
)
from agentbus.trace.redaction import (
    HIDDEN_CONTENT,
    PRIVATE_PATH,
    REDACTED,
    RedactionMetadata,
    SanitizedDocument,
    configuration_fingerprint,
    contains_secret_material,
    sanitize_document,
    sanitize_text,
)
from agentbus.trace.spans import (
    DeterministicSequence,
    trace_id_for_run,
    trace_item_id,
)
from agentbus.trace.storage import ContentAddressedStore

__all__ = [
    "ReplayMode",
    "TRACE_SCHEMA_NAME",
    "TRACE_SCHEMA_VERSION",
    "DeterministicSequence",
    "BLOB_SCHEMA_VERSION",
    "BlobMetadata",
    "ContentAddressedStore",
    "EventStreamRange",
    "HIDDEN_CONTENT",
    "PRIVATE_PATH",
    "PROVENANCE_INTEGRITY_ALGORITHM",
    "PROVENANCE_SCHEMA_VERSION",
    "REDACTED",
    "ProvenanceBuilder",
    "ProvenanceIntegrityEntry",
    "ProvenanceManifest",
    "ProviderRouteProvenance",
    "RedactionMetadata",
    "ReplayabilityLevel",
    "RetentionClass",
    "StoredBlob",
    "StateStoreTraceSink",
    "Trace",
    "TraceArtifactReference",
    "TraceCheckpoint",
    "TraceContext",
    "TraceError",
    "TraceEvent",
    "TraceEventType",
    "TraceFailure",
    "TraceInput",
    "TraceIntegrityError",
    "TraceLink",
    "TraceLinkType",
    "TraceNotFoundError",
    "TraceObjectTooLargeError",
    "TraceOutput",
    "TraceReplayMetadata",
    "TraceRecorder",
    "TraceRecordingError",
    "TraceSecretRejectedError",
    "TraceResourceUsage",
    "TraceSpan",
    "TraceSpanType",
    "TraceStatus",
    "TraceStorageError",
    "TraceSink",
    "TraceValidationError",
    "TraceValueReference",
    "ToolDescriptorProvenance",
    "SanitizedDocument",
    "configuration_fingerprint",
    "contains_secret_material",
    "copy_trace_context",
    "current_trace_context",
    "reset_trace_context",
    "set_trace_context",
    "sanitize_document",
    "sanitize_text",
    "trace_context",
    "trace_id_for_run",
    "trace_item_id",
    "verify_provenance",
]
