from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path

from agentbus.config import SUPPORTED_PROVIDERS
from agentbus.execution.state_store import StateStore


class BootstrapError(RuntimeError):
    """Raised when safe bootstrap cannot proceed."""


@dataclass(frozen=True)
class BootstrapResult:
    root: Path
    config_file: Path
    state_database: Path
    provider: str
    dry_run: bool
    created: list[Path] = field(default_factory=list)
    planned: list[Path] = field(default_factory=list)


def initialize(
    *,
    workspace: str | Path = ".",
    local: bool = False,
    provider: str = "ollama",
    dry_run: bool = False,
    force: bool = False,
    with_env_example: bool = False,
    root: str | Path | None = None,
) -> BootstrapResult:
    if provider not in SUPPORTED_PROVIDERS:
        choices = ", ".join(SUPPORTED_PROVIDERS)
        raise BootstrapError(f"Provider must be one of: {choices}.")
    workspace_path = Path(workspace).expanduser().resolve()
    if root is not None:
        config_root = Path(root).expanduser().resolve()
    elif local:
        config_root = workspace_path / ".agentbus"
    else:
        config_root = Path(
            os.getenv("AGENTBUS_HOME", str(Path.home() / ".agentbus"))
        ).expanduser().resolve()

    config_file = config_root / "config.toml"
    state_database = config_root / "state.db"
    runtime_dirs = [config_root, config_root / "runs", config_root / "evaluations"]
    if not local:
        runtime_dirs.append(config_root / "worktrees")
    env_example = config_root / ".env.example"
    planned = [*runtime_dirs, config_file, state_database]
    if with_env_example:
        planned.append(env_example)

    if config_file.exists() and not force and not dry_run:
        raise BootstrapError(
            f"Configuration already exists: {config_file}. Use --force to replace it."
        )
    if dry_run:
        return BootstrapResult(
            root=config_root,
            config_file=config_file,
            state_database=state_database,
            provider=provider,
            dry_run=True,
            planned=planned,
        )

    created: list[Path] = []
    for directory in runtime_dirs:
        if not directory.exists():
            directory.mkdir(parents=True, exist_ok=True)
            created.append(directory)

    config_text = _config_template(
        workspace=workspace_path,
        root=config_root,
        provider=provider,
        local=local,
    )
    config_file.write_text(config_text, encoding="utf-8", newline="\n")
    created.append(config_file)

    if with_env_example:
        if not env_example.exists() or force:
            env_example.write_text(_environment_template(provider), encoding="utf-8")
            created.append(env_example)

    StateStore(state_database)
    if state_database not in created:
        created.append(state_database)
    return BootstrapResult(
        root=config_root,
        config_file=config_file,
        state_database=state_database,
        provider=provider,
        dry_run=False,
        created=created,
        planned=planned,
    )


def _config_template(*, workspace: Path, root: Path, provider: str, local: bool) -> str:
    lines = [
        "# Generated by agentbus init. This file contains no credentials.",
        "[agentbus]",
        f"provider_name = {json.dumps(provider)}",
        f"workspace_dir = {json.dumps(str(workspace))}",
        f"runs_dir = {json.dumps(str(root / 'runs'))}",
        f"state_dir = {json.dumps(str(root))}",
        'state_db = "state.db"',
    ]
    if not local:
        lines.append(f"worktree_root = {json.dumps(str(root / 'worktrees'))}")
    if provider == "azure":
        lines.extend(
            [
                "",
                "# Set Azure endpoint, key, and deployment routes in the process",
                "# environment. Never put a real API key in this file.",
            ]
        )
    elif provider == "ollama":
        lines.extend(
            [
                "",
                "# Ollama is the offline-first default. AgentBus never downloads models.",
                '# ollama_url = "http://localhost:11434/api/generate"',
            ]
        )
    else:
        lines.extend(
            [
                "",
                "# Deterministic mode is network-free and requires no credentials.",
                '# deterministic_profile = "python-calculator"',
            ]
        )
    return "\n".join(lines) + "\n"


def _environment_template(provider: str) -> str:
    common = "# Example only. Copy values into your process environment explicitly.\n"
    if provider == "azure":
        return common + (
            "AZURE_OPENAI_ENDPOINT=https://YOUR-RESOURCE.openai.azure.com\n"
            "AZURE_OPENAI_API_KEY=replace-with-a-real-key-outside-source-control\n"
            "AZURE_OPENAI_DEFAULT_DEPLOYMENT=your-deployment\n"
        )
    if provider == "deterministic":
        return common + (
            "AGENTBUS_DETERMINISTIC_PROFILE=python-calculator\n"
            "AGENTBUS_DETERMINISTIC_LATENCY_SECONDS=0\n"
        )
    return common + (
        "AGENTBUS_PROVIDER=ollama\n"
        "AGENTBUS_OLLAMA_URL=http://localhost:11434/api/generate\n"
        "AGENTBUS_MODEL=qwen2.5-coder:7b\n"
    )
