"""Dependency-free identities shared by generated AgentBus protocols."""

CONTROL_PROTOCOL_VERSION = "1.0"
TOOL_PROTOCOL_NAME = "agentbus.tool"
TOOL_PROTOCOL_MAJOR = 1
TOOL_PROTOCOL_MINOR = 0
TOOL_PROTOCOL_VERSION = f"{TOOL_PROTOCOL_MAJOR}.{TOOL_PROTOCOL_MINOR}"

__all__ = [
    "CONTROL_PROTOCOL_VERSION",
    "TOOL_PROTOCOL_MAJOR",
    "TOOL_PROTOCOL_MINOR",
    "TOOL_PROTOCOL_NAME",
    "TOOL_PROTOCOL_VERSION",
]
